---
- name: Install Apache web server
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache2 and enable at boot
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes